// Code generated by mockery v2.33.3. DO NOT EDIT.

package repositories

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"

	uuid "github.com/google/uuid"
)

// MockBillingRepository is an autogenerated mock type for the BillingRepository type
type MockBillingRepository struct {
	mock.Mock
}

type MockBillingRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBillingRepository) EXPECT() *MockBillingRepository_Expecter {
	return &MockBillingRepository_Expecter{mock: &_m.Mock}
}

// GetOutstanding provides a mock function with given fields: ctx, loanId
func (_m *MockBillingRepository) GetOutstanding(ctx context.Context, loanId uuid.UUID) (float64, error) {
	ret := _m.Called(ctx, loanId)

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (float64, error)); ok {
		return rf(ctx, loanId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) float64); ok {
		r0 = rf(ctx, loanId)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, loanId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBillingRepository_GetOutstanding_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOutstanding'
type MockBillingRepository_GetOutstanding_Call struct {
	*mock.Call
}

// GetOutstanding is a helper method to define mock.On call
//   - ctx context.Context
//   - loanId uuid.UUID
func (_e *MockBillingRepository_Expecter) GetOutstanding(ctx interface{}, loanId interface{}) *MockBillingRepository_GetOutstanding_Call {
	return &MockBillingRepository_GetOutstanding_Call{Call: _e.mock.On("GetOutstanding", ctx, loanId)}
}

func (_c *MockBillingRepository_GetOutstanding_Call) Run(run func(ctx context.Context, loanId uuid.UUID)) *MockBillingRepository_GetOutstanding_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockBillingRepository_GetOutstanding_Call) Return(outstandingAmount float64, err error) *MockBillingRepository_GetOutstanding_Call {
	_c.Call.Return(outstandingAmount, err)
	return _c
}

func (_c *MockBillingRepository_GetOutstanding_Call) RunAndReturn(run func(context.Context, uuid.UUID) (float64, error)) *MockBillingRepository_GetOutstanding_Call {
	_c.Call.Return(run)
	return _c
}

// IsDelinquent provides a mock function with given fields: ctx, loanId, currentDt
func (_m *MockBillingRepository) IsDelinquent(ctx context.Context, loanId uuid.UUID, currentDt time.Time) (bool, error) {
	ret := _m.Called(ctx, loanId, currentDt)

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) (bool, error)); ok {
		return rf(ctx, loanId, currentDt)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) bool); ok {
		r0 = rf(ctx, loanId, currentDt)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, time.Time) error); ok {
		r1 = rf(ctx, loanId, currentDt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBillingRepository_IsDelinquent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsDelinquent'
type MockBillingRepository_IsDelinquent_Call struct {
	*mock.Call
}

// IsDelinquent is a helper method to define mock.On call
//   - ctx context.Context
//   - loanId uuid.UUID
//   - currentDt time.Time
func (_e *MockBillingRepository_Expecter) IsDelinquent(ctx interface{}, loanId interface{}, currentDt interface{}) *MockBillingRepository_IsDelinquent_Call {
	return &MockBillingRepository_IsDelinquent_Call{Call: _e.mock.On("IsDelinquent", ctx, loanId, currentDt)}
}

func (_c *MockBillingRepository_IsDelinquent_Call) Run(run func(ctx context.Context, loanId uuid.UUID, currentDt time.Time)) *MockBillingRepository_IsDelinquent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(time.Time))
	})
	return _c
}

func (_c *MockBillingRepository_IsDelinquent_Call) Return(isDelinquent bool, err error) *MockBillingRepository_IsDelinquent_Call {
	_c.Call.Return(isDelinquent, err)
	return _c
}

func (_c *MockBillingRepository_IsDelinquent_Call) RunAndReturn(run func(context.Context, uuid.UUID, time.Time) (bool, error)) *MockBillingRepository_IsDelinquent_Call {
	_c.Call.Return(run)
	return _c
}

// MakePayment provides a mock function with given fields: ctx, loanId, paymentAmount, paymentDt
func (_m *MockBillingRepository) MakePayment(ctx context.Context, loanId uuid.UUID, paymentAmount float64, paymentDt time.Time) error {
	ret := _m.Called(ctx, loanId, paymentAmount, paymentDt)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, float64, time.Time) error); ok {
		r0 = rf(ctx, loanId, paymentAmount, paymentDt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBillingRepository_MakePayment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MakePayment'
type MockBillingRepository_MakePayment_Call struct {
	*mock.Call
}

// MakePayment is a helper method to define mock.On call
//   - ctx context.Context
//   - loanId uuid.UUID
//   - paymentAmount float64
//   - paymentDt time.Time
func (_e *MockBillingRepository_Expecter) MakePayment(ctx interface{}, loanId interface{}, paymentAmount interface{}, paymentDt interface{}) *MockBillingRepository_MakePayment_Call {
	return &MockBillingRepository_MakePayment_Call{Call: _e.mock.On("MakePayment", ctx, loanId, paymentAmount, paymentDt)}
}

func (_c *MockBillingRepository_MakePayment_Call) Run(run func(ctx context.Context, loanId uuid.UUID, paymentAmount float64, paymentDt time.Time)) *MockBillingRepository_MakePayment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(float64), args[3].(time.Time))
	})
	return _c
}

func (_c *MockBillingRepository_MakePayment_Call) Return(err error) *MockBillingRepository_MakePayment_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBillingRepository_MakePayment_Call) RunAndReturn(run func(context.Context, uuid.UUID, float64, time.Time) error) *MockBillingRepository_MakePayment_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBillingRepository creates a new instance of MockBillingRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBillingRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBillingRepository {
	mock := &MockBillingRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
